### PR TITLE
[doc] Add docs badge to README

### PR DESCRIPTION
**Pull request by rrrene**
Hi there,

I want to propose to add this badge to the README to show off inline-documentation: [Inline docs](http://inch-ci.org/github/foreverjs/forever)

The badge links to [Inch CI](http://inch-ci.org) and shows an evaluation by [InchJS](http://trivelop.de/inchjs), a project that tries to raise the visibility of inline-docs in Open Source to encourage aspiring programmers to document their code. So far over 500 **Ruby** projects are sporting these badges to raise awareness for the importance of inline-docs and to show potential contributors that they can expect a certain level of code documentation when they dive into your code.

I would really like to do the same for the **JavaScript** community and roll out support for JS over the coming weeks. Although this is "only" a passion project, I really would like to hear your thoughts, critique and suggestions. Your status page is http://inch-ci.org/github/foreverjs/forever

What do you think?

### CODE REVIEW

**Comment by jcrugzz** [comment]
@rrrene this seems interesting, It may make people less adverse to jumping into the code and seeing whats happening :). cc @indexzero

**Comment by indexzero** [comment]
Oh wow. This is really cool.

**Comment by indexzero** [comment]
@rrrene yeah InchJS is really neat. I look forward to seeing it grow! https://github.com/rrrene/inch/issues/27

**Comment by rrrene** [comment]
> It may make people less adverse to jumping into the code and seeing whats happening

That is exactly what this is about. I should include something like this in future PRs. 

Thanks for giving this a shot!

**Pull request merged**
